server:
  port: 7788
spring:
  datasource:
    url: jdbc:h2:mem:workflowdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  #   schema:
  #     - classpath:sql/load_script.sql
  #   sql-script-encoding: utf-8
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  h2:
    console:
      web-allow-others: true
      path: /h2-console
      enabled: true

jwt:
  secret: 993e7a590cf0
  expiration: 500